CREATE DATABASE IF NOT EXISTS KIRI_AI_DEMO;

CREATE SCHEMA IF NOT EXISTS KIRI_AI_DEMO.RAW;
CREATE SCHEMA IF NOT EXISTS KIRI_AI_DEMO.MART;

CREATE TABLE IF NOT EXISTS KIRI_AI_DEMO.RAW.DAILY_NAV (
    TRADE_DATE DATE NOT NULL,
    FUND_ID VARCHAR(50) NOT NULL,
    NAV NUMBER(18, 6) NOT NULL,
    BENCHMARK_NAV NUMBER(18, 6) NOT NULL,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
