CREATE OR REPLACE VIEW KIRI_AI_DEMO.MART.V_DAILY_PERFORMANCE AS
WITH base AS (
    SELECT
        TRADE_DATE,
        FUND_ID,
        NAV,
        BENCHMARK_NAV,
        NAV / LAG(NAV) OVER (
            PARTITION BY FUND_ID
            ORDER BY TRADE_DATE
        ) - 1 AS DAILY_RETURN,
        BENCHMARK_NAV / LAG(BENCHMARK_NAV) OVER (
            PARTITION BY FUND_ID
            ORDER BY TRADE_DATE
        ) - 1 AS BENCHMARK_DAILY_RETURN
    FROM KIRI_AI_DEMO.RAW.DAILY_NAV
),
with_peak AS (
    SELECT
        *,
        MAX(NAV) OVER (
            PARTITION BY FUND_ID
            ORDER BY TRADE_DATE
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS RUNNING_PEAK
    FROM base
)
SELECT
    TRADE_DATE,
    FUND_ID,
    NAV,
    BENCHMARK_NAV,
    DAILY_RETURN,
    BENCHMARK_DAILY_RETURN,
    NAV / RUNNING_PEAK - 1 AS DRAWDOWN
FROM with_peak;


CREATE OR REPLACE VIEW KIRI_AI_DEMO.MART.V_FUND_SUMMARY AS
WITH ranked AS (
    SELECT
        TRADE_DATE,
        FUND_ID,
        NAV,
        BENCHMARK_NAV,
        ROW_NUMBER() OVER (
            PARTITION BY FUND_ID
            ORDER BY TRADE_DATE
        ) AS RN_FIRST,
        ROW_NUMBER() OVER (
            PARTITION BY FUND_ID
            ORDER BY TRADE_DATE DESC
        ) AS RN_LAST
    FROM KIRI_AI_DEMO.RAW.DAILY_NAV
),
bounds AS (
    SELECT
        FUND_ID,
        MAX(IFF(RN_FIRST = 1, TRADE_DATE, NULL)) AS PERIOD_START,
        MAX(IFF(RN_LAST = 1, TRADE_DATE, NULL)) AS PERIOD_END,
        MAX(IFF(RN_FIRST = 1, NAV, NULL)) AS FIRST_NAV,
        MAX(IFF(RN_LAST = 1, NAV, NULL)) AS LAST_NAV,
        MAX(IFF(RN_FIRST = 1, BENCHMARK_NAV, NULL)) AS FIRST_BENCHMARK_NAV,
        MAX(IFF(RN_LAST = 1, BENCHMARK_NAV, NULL)) AS LAST_BENCHMARK_NAV
    FROM ranked
    GROUP BY FUND_ID
),
risk AS (
    SELECT
        FUND_ID,
        STDDEV_SAMP(DAILY_RETURN) * SQRT(252) AS ANNUALIZED_VOLATILITY,
        MIN(DRAWDOWN) AS MAX_DRAWDOWN,
        COUNT(*) AS OBSERVATIONS
    FROM KIRI_AI_DEMO.MART.V_DAILY_PERFORMANCE
    GROUP BY FUND_ID
)
SELECT
    b.FUND_ID,
    b.PERIOD_START,
    b.PERIOD_END,
    b.LAST_NAV / b.FIRST_NAV - 1 AS TOTAL_RETURN,
    b.LAST_BENCHMARK_NAV / b.FIRST_BENCHMARK_NAV - 1 AS BENCHMARK_RETURN,
    (b.LAST_NAV / b.FIRST_NAV - 1)
        - (b.LAST_BENCHMARK_NAV / b.FIRST_BENCHMARK_NAV - 1)
        AS EXCESS_RETURN,
    r.ANNUALIZED_VOLATILITY,
    r.MAX_DRAWDOWN,
    r.OBSERVATIONS
FROM bounds b
JOIN risk r
    ON b.FUND_ID = r.FUND_ID;
